import { init } from "@paralleldrive/cuid2";
import { relations, sql } from "drizzle-orm";
import { index, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

let cuidGenerator: (() => string) | undefined;

const getCuidGenerator = () => {
  if (!cuidGenerator) {
    // Lazily initialize to avoid calling crypto APIs at module load (Cloudflare restriction)
    cuidGenerator = init({
      random: () => crypto.getRandomValues(new Uint32Array(1))[0] / 0xffffffff,
      length: 10,
    });
  }
  return cuidGenerator;
};

const generateId = () => getCuidGenerator()();

// =============================================================================
// BetterAuth Tables (generated by @better-auth/cli)
// =============================================================================

export const userRoles = ["waitlist", "user", "admin"] as const;
export type UserRole = (typeof userRoles)[number];

export const user = sqliteTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: integer("email_verified", { mode: "boolean" }).default(false).notNull(),
  image: text("image"),
  role: text("role").$type<UserRole>().default("waitlist").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
});

export const session = sqliteTable("session", {
  id: text("id").primaryKey(),
  expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(),
  token: text("token").notNull().unique(),
  createdAt: integer("created_at", { mode: "timestamp_ms" })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" })
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
});

export const account = sqliteTable("account", {
  id: text("id").primaryKey(),
  accountId: text("account_id").notNull(),
  providerId: text("provider_id").notNull(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  idToken: text("id_token"),
  accessTokenExpiresAt: integer("access_token_expires_at", {
    mode: "timestamp_ms",
  }),
  refreshTokenExpiresAt: integer("refresh_token_expires_at", {
    mode: "timestamp_ms",
  }),
  scope: text("scope"),
  password: text("password"),
  createdAt: integer("created_at", { mode: "timestamp_ms" })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" })
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
});

export const verification = sqliteTable("verification", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
});

export const deviceCode = sqliteTable("device_code", {
  id: text("id").primaryKey(),
  deviceCode: text("device_code").notNull(),
  userCode: text("user_code").notNull(),
  userId: text("user_id"),
  expiresAt: integer("expires_at", { mode: "timestamp_ms" }).notNull(),
  status: text("status").notNull(),
  lastPolledAt: integer("last_polled_at", { mode: "timestamp_ms" }),
  pollingInterval: integer("polling_interval"),
  clientId: text("client_id"),
  scope: text("scope"),
});

// =============================================================================
// AgentLogs tables (with userId for multi-tenancy)
// =============================================================================
export const repos = sqliteTable("repos", {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => generateId()),
  repo: text("repo").notNull().unique(),
  lastActivity: text("last_activity"),
  createdAt: integer("created_at", { mode: "timestamp" })
    .notNull()
    .$defaultFn(() => new Date()),
});

export const transcripts = sqliteTable(
  "transcripts",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => generateId()),
    repoId: text("repo_id").references(() => repos.id, { onDelete: "cascade" }),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),

    sha256: text("sha256").notNull(),
    transcriptId: text("transcript_id").notNull(),
    source: text("source").notNull(),
    createdAt: integer("created_at", { mode: "timestamp" })
      .notNull()
      .$defaultFn(() => new Date()),
    preview: text("preview"),
    summary: text("summary"),
    model: text("model"),
    costUsd: real("cost_usd").notNull(),
    blendedTokens: integer("blended_tokens").notNull(),
    messageCount: integer("message_count").notNull(),
    toolCount: integer("tool_count").notNull().default(0),
    userMessageCount: integer("user_message_count").notNull().default(0),
    filesChanged: integer("files_changed").notNull().default(0),
    linesAdded: integer("lines_added").notNull().default(0),
    linesRemoved: integer("lines_removed").notNull().default(0),
    inputTokens: integer("input_tokens").notNull(),
    cachedInputTokens: integer("cached_input_tokens").notNull(),
    outputTokens: integer("output_tokens").notNull(),
    reasoningOutputTokens: integer("reasoning_output_tokens").notNull(),
    totalTokens: integer("total_tokens").notNull(),
    relativeCwd: text("relative_cwd"),
    branch: text("branch"),
    cwd: text("cwd"),

    updatedAt: integer("updated_at", { mode: "timestamp_ms" })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => ({
    // Note: SQLite unique index on (repoId, transcriptId) where repoId can be null
    // Multiple rows with (null, transcriptId) are allowed, so we need separate constraint
    repoTranscriptIdx: uniqueIndex("idx_repo_transcript").on(table.repoId, table.transcriptId),
    userTranscriptIdx: uniqueIndex("idx_user_transcript").on(table.userId, table.transcriptId),
    repoIdx: index("idx_repo_id").on(table.repoId),
    userIdx: index("idx_user_id").on(table.userId),
  }),
);

export const commitTracking = sqliteTable("commit_tracking", {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => generateId()),
  userId: text("user_id").notNull(),
  sessionId: text("session_id").notNull(),
  repoPath: text("repo_path").notNull(),
  timestamp: text("timestamp").notNull(),
  createdAt: integer("created_at", { mode: "timestamp" })
    .notNull()
    .$defaultFn(() => new Date()),
});

// =============================================================================
// Blob Storage Tables (content-addressed deduplication)
// =============================================================================

/**
 * Global blob storage - content-addressed by SHA256
 * Each unique blob (image/screenshot) is stored once
 */
export const blobs = sqliteTable("blobs", {
  sha256: text("sha256").primaryKey(),
  mediaType: text("media_type").notNull(),
  size: integer("size").notNull(),
  createdAt: integer("created_at", { mode: "timestamp" })
    .notNull()
    .$defaultFn(() => new Date()),
});

/**
 * Junction table linking transcripts to blobs
 * Enables access control - user can access blob if they own a transcript that references it
 */
export const transcriptBlobs = sqliteTable(
  "transcript_blobs",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => generateId()),
    transcriptId: text("transcript_id")
      .notNull()
      .references(() => transcripts.id, { onDelete: "cascade" }),
    sha256: text("sha256")
      .notNull()
      .references(() => blobs.sha256, { onDelete: "cascade" }),
  },
  (table) => ({
    transcriptBlobUnique: uniqueIndex("idx_transcript_blob_unique").on(table.transcriptId, table.sha256),
    sha256Idx: index("idx_transcript_blobs_sha256").on(table.sha256),
  }),
);

// =============================================================================
// Relations (for Drizzle queries with joins)
// =============================================================================

// BetterAuth relations
export const userRelations = relations(user, ({ many }) => ({
  sessions: many(session),
  accounts: many(account),
  transcripts: many(transcripts),
}));

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, {
    fields: [session.userId],
    references: [user.id],
  }),
}));

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, {
    fields: [account.userId],
    references: [user.id],
  }),
}));

// AgentLogs relations
export const reposRelations = relations(repos, ({ many }) => ({
  transcripts: many(transcripts),
}));

export const transcriptsRelations = relations(transcripts, ({ one, many }) => ({
  user: one(user, {
    fields: [transcripts.userId],
    references: [user.id],
  }),
  repo: one(repos, {
    fields: [transcripts.repoId],
    references: [repos.id],
  }),
  transcriptBlobs: many(transcriptBlobs),
}));

// Blob relations
export const blobsRelations = relations(blobs, ({ many }) => ({
  transcriptBlobs: many(transcriptBlobs),
}));

export const transcriptBlobsRelations = relations(transcriptBlobs, ({ one }) => ({
  transcript: one(transcripts, {
    fields: [transcriptBlobs.transcriptId],
    references: [transcripts.id],
  }),
  blob: one(blobs, {
    fields: [transcriptBlobs.sha256],
    references: [blobs.sha256],
  }),
}));
