import { init } from "@paralleldrive/cuid2";
import { relations } from "drizzle-orm";
import { boolean, doublePrecision, index, integer, pgTable, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core";

let cuidGenerator: (() => string) | undefined;

const getCuidGenerator = () => {
  if (!cuidGenerator) {
    // Lazily initialize to avoid calling crypto APIs at module load (Cloudflare restriction)
    cuidGenerator = init();
  }
  return cuidGenerator;
};

const generateId = () => getCuidGenerator()();

// =============================================================================
// BetterAuth Tables (generated by @better-auth/cli)
// =============================================================================

export const userRoles = ["waitlist", "user", "admin"] as const;
export type UserRole = (typeof userRoles)[number];

export const visibilityOptions = ["private", "team", "public"] as const;
export type VisibilityOption = (typeof visibilityOptions)[number];

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  username: text("username").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").default(false).notNull(),
  image: text("image"),
  role: text("role").$type<UserRole>().default("user").notNull(),
  welcomeEmailSentAt: timestamp("welcome_email_sent_at", { withTimezone: true, mode: "date" }),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" })
    .defaultNow()
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
});

export const session = pgTable("session", {
  id: text("id").primaryKey(),
  expiresAt: timestamp("expires_at", { withTimezone: true, mode: "date" }).notNull(),
  token: text("token").notNull().unique(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" })
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
});

export const account = pgTable("account", {
  id: text("id").primaryKey(),
  accountId: text("account_id").notNull(),
  providerId: text("provider_id").notNull(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  idToken: text("id_token"),
  accessTokenExpiresAt: timestamp("access_token_expires_at", {
    withTimezone: true,
    mode: "date",
  }),
  refreshTokenExpiresAt: timestamp("refresh_token_expires_at", {
    withTimezone: true,
    mode: "date",
  }),
  scope: text("scope"),
  password: text("password"),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" })
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
});

export const verification = pgTable("verification", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: timestamp("expires_at", { withTimezone: true, mode: "date" }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "date" }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" })
    .defaultNow()
    .$onUpdate(() => /* @__PURE__ */ new Date())
    .notNull(),
});

export const deviceCode = pgTable("device_code", {
  id: text("id").primaryKey(),
  deviceCode: text("device_code").notNull(),
  userCode: text("user_code").notNull(),
  userId: text("user_id"),
  expiresAt: timestamp("expires_at", { withTimezone: true, mode: "date" }).notNull(),
  status: text("status").notNull(),
  lastPolledAt: timestamp("last_polled_at", { withTimezone: true, mode: "date" }),
  pollingInterval: integer("polling_interval"),
  clientId: text("client_id"),
  scope: text("scope"),
});

// =============================================================================
// AgentLogs tables (with userId for multi-tenancy)
// =============================================================================
export const repos = pgTable("repos", {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => generateId()),
  repo: text("repo").notNull().unique(),
  lastActivity: text("last_activity"),
  isPublic: boolean("is_public"),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
    .notNull()
    .$defaultFn(() => new Date()),
});

export const transcripts = pgTable(
  "transcripts",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => generateId()),
    repoId: text("repo_id").references(() => repos.id, { onDelete: "cascade" }),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),

    // Sharing/visibility
    visibility: text("visibility").$type<VisibilityOption>().default("private").notNull(),
    sharedWithTeamId: text("shared_with_team_id").references(() => teams.id, { onDelete: "set null" }),

    sha256: text("sha256").notNull(),
    transcriptId: text("transcript_id").notNull(),
    source: text("source").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
      .notNull()
      .$defaultFn(() => new Date()),
    preview: text("preview"),
    summary: text("summary"),
    model: text("model"),
    clientVersion: text("client_version"),
    costUsd: doublePrecision("cost_usd").notNull(),
    blendedTokens: integer("blended_tokens").notNull(),
    messageCount: integer("message_count").notNull(),
    toolCount: integer("tool_count").notNull().default(0),
    userMessageCount: integer("user_message_count").notNull().default(0),
    filesChanged: integer("files_changed").notNull().default(0),
    linesAdded: integer("lines_added").notNull().default(0),
    linesRemoved: integer("lines_removed").notNull().default(0),
    linesModified: integer("lines_modified").notNull().default(0),
    transcriptVersion: integer("transcript_version").notNull().default(1),
    inputTokens: integer("input_tokens").notNull(),
    cachedInputTokens: integer("cached_input_tokens").notNull(),
    outputTokens: integer("output_tokens").notNull(),
    reasoningOutputTokens: integer("reasoning_output_tokens").notNull(),
    totalTokens: integer("total_tokens").notNull(),
    relativeCwd: text("relative_cwd"),
    branch: text("branch"),
    cwd: text("cwd"),
    previewBlobSha256: text("preview_blob_sha256"),

    updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" })
      .defaultNow()
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => ({
    repoTranscriptIdx: uniqueIndex("idx_repo_transcript").on(table.repoId, table.transcriptId),
    userTranscriptIdx: uniqueIndex("idx_user_transcript").on(table.userId, table.transcriptId),
    repoIdx: index("idx_repo_id").on(table.repoId),
    userIdx: index("idx_user_id").on(table.userId),
    userCreatedAtIdx: index("idx_user_created_at").on(table.userId, table.createdAt, table.id),
  }),
);

export const commitTracking = pgTable(
  "commit_tracking",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => generateId()),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    transcriptId: text("transcript_id")
      .notNull()
      .references(() => transcripts.id, { onDelete: "cascade" }),
    repoPath: text("repo_path").notNull(),
    timestamp: text("timestamp").notNull(),
    commitSha: text("commit_sha"),
    commitTitle: text("commit_title"),
    branch: text("branch"),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
      .notNull()
      .$defaultFn(() => new Date()),
  },
  (table) => ({
    transcriptIdx: index("idx_commit_tracking_transcript").on(table.transcriptId),
    userIdx: index("idx_commit_tracking_user").on(table.userId),
  }),
);

// =============================================================================
// Blob Storage Tables (content-addressed deduplication)
// =============================================================================

/**
 * Global blob storage - content-addressed by SHA256
 * Each unique blob (image/screenshot) is stored once
 */
export const blobs = pgTable("blobs", {
  sha256: text("sha256").primaryKey(),
  mediaType: text("media_type").notNull(),
  size: integer("size").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
    .notNull()
    .$defaultFn(() => new Date()),
});

/**
 * Junction table linking transcripts to blobs
 * Enables access control - user can access blob if they own a transcript that references it
 */
export const transcriptBlobs = pgTable(
  "transcript_blobs",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => generateId()),
    transcriptId: text("transcript_id")
      .notNull()
      .references(() => transcripts.id, { onDelete: "cascade" }),
    sha256: text("sha256")
      .notNull()
      .references(() => blobs.sha256, { onDelete: "cascade" }),
  },
  (table) => ({
    transcriptBlobUnique: uniqueIndex("idx_transcript_blob_unique").on(table.transcriptId, table.sha256),
    sha256Idx: index("idx_transcript_blobs_sha256").on(table.sha256),
  }),
);

// =============================================================================
// Teams Tables (manual team invites for transcript sharing)
// =============================================================================

/**
 * Teams - each team has one owner
 * Name is auto-generated as "[Owner]'s Team"
 */
export const teams = pgTable("teams", {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => generateId()),
  name: text("name").notNull(),
  ownerId: text("owner_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
    .notNull()
    .$defaultFn(() => new Date()),
  updatedAt: timestamp("updated_at", { withTimezone: true, mode: "date" })
    .defaultNow()
    .$onUpdate(() => new Date())
    .notNull(),
});

/**
 * Team members - owner is ALSO added here for simpler access control queries
 * UNIQUE(teamId, userId) allows future multi-team support
 * App code enforces 0-1 team for MVP
 */
export const teamMembers = pgTable(
  "team_members",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => generateId()),
    teamId: text("team_id")
      .notNull()
      .references(() => teams.id, { onDelete: "cascade" }),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    joinedAt: timestamp("joined_at", { withTimezone: true, mode: "date" })
      .notNull()
      .$defaultFn(() => new Date()),
  },
  (table) => ({
    teamUserUnique: uniqueIndex("idx_team_members_unique").on(table.teamId, table.userId),
    userIdx: index("idx_team_members_user").on(table.userId),
    teamIdx: index("idx_team_members_team").on(table.teamId),
  }),
);

/**
 * Team invites - invite links with 7-day expiry
 * One active invite per team (generating new one replaces old)
 */
export const teamInvites = pgTable(
  "team_invites",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => generateId()),
    teamId: text("team_id")
      .notNull()
      .references(() => teams.id, { onDelete: "cascade" }),
    code: text("code").notNull().unique(),
    expiresAt: timestamp("expires_at", { withTimezone: true, mode: "date" }).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true, mode: "date" })
      .notNull()
      .$defaultFn(() => new Date()),
  },
  (table) => ({
    teamIdx: index("idx_team_invites_team").on(table.teamId),
  }),
);

// =============================================================================
// Relations (for Drizzle queries with joins)
// =============================================================================

// BetterAuth relations
export const userRelations = relations(user, ({ many }) => ({
  sessions: many(session),
  accounts: many(account),
  transcripts: many(transcripts),
  teamMemberships: many(teamMembers),
  ownedTeams: many(teams),
}));

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, {
    fields: [session.userId],
    references: [user.id],
  }),
}));

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, {
    fields: [account.userId],
    references: [user.id],
  }),
}));

// AgentLogs relations
export const reposRelations = relations(repos, ({ many }) => ({
  transcripts: many(transcripts),
}));

export const transcriptsRelations = relations(transcripts, ({ one, many }) => ({
  user: one(user, {
    fields: [transcripts.userId],
    references: [user.id],
  }),
  repo: one(repos, {
    fields: [transcripts.repoId],
    references: [repos.id],
  }),
  sharedWithTeam: one(teams, {
    fields: [transcripts.sharedWithTeamId],
    references: [teams.id],
  }),
  transcriptBlobs: many(transcriptBlobs),
  commits: many(commitTracking),
}));

export const commitTrackingRelations = relations(commitTracking, ({ one }) => ({
  user: one(user, {
    fields: [commitTracking.userId],
    references: [user.id],
  }),
  transcript: one(transcripts, {
    fields: [commitTracking.transcriptId],
    references: [transcripts.id],
  }),
}));

// Blob relations
export const blobsRelations = relations(blobs, ({ many }) => ({
  transcriptBlobs: many(transcriptBlobs),
}));

export const transcriptBlobsRelations = relations(transcriptBlobs, ({ one }) => ({
  transcript: one(transcripts, {
    fields: [transcriptBlobs.transcriptId],
    references: [transcripts.id],
  }),
  blob: one(blobs, {
    fields: [transcriptBlobs.sha256],
    references: [blobs.sha256],
  }),
}));

// Team relations
export const teamsRelations = relations(teams, ({ one, many }) => ({
  owner: one(user, {
    fields: [teams.ownerId],
    references: [user.id],
  }),
  members: many(teamMembers),
  invites: many(teamInvites),
  sharedTranscripts: many(transcripts),
}));

export const teamMembersRelations = relations(teamMembers, ({ one }) => ({
  team: one(teams, {
    fields: [teamMembers.teamId],
    references: [teams.id],
  }),
  user: one(user, {
    fields: [teamMembers.userId],
    references: [user.id],
  }),
}));

export const teamInvitesRelations = relations(teamInvites, ({ one }) => ({
  team: one(teams, {
    fields: [teamInvites.teamId],
    references: [teams.id],
  }),
}));
