import { sqliteTable, text, integer, real } from 'drizzle-orm/sqlite-core';
import { relations, sql } from 'drizzle-orm';

// =============================================================================
// BetterAuth Tables (generated by @better-auth/cli)
// =============================================================================

export const user = sqliteTable('user', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: integer('email_verified', { mode: 'boolean' })
    .default(false)
    .notNull(),
  image: text('image'),
  createdAt: integer('created_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .$onUpdate(() => new Date())
    .notNull(),
});

export const session = sqliteTable('session', {
  id: text('id').primaryKey(),
  expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
  token: text('token').notNull().unique(),
  createdAt: integer('created_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
    .$onUpdate(() => new Date())
    .notNull(),
  ipAddress: text('ip_address'),
  userAgent: text('user_agent'),
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
});

export const account = sqliteTable('account', {
  id: text('id').primaryKey(),
  accountId: text('account_id').notNull(),
  providerId: text('provider_id').notNull(),
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  accessToken: text('access_token'),
  refreshToken: text('refresh_token'),
  idToken: text('id_token'),
  accessTokenExpiresAt: integer('access_token_expires_at', {
    mode: 'timestamp_ms',
  }),
  refreshTokenExpiresAt: integer('refresh_token_expires_at', {
    mode: 'timestamp_ms',
  }),
  scope: text('scope'),
  password: text('password'),
  createdAt: integer('created_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
    .$onUpdate(() => new Date())
    .notNull(),
});

export const verification = sqliteTable('verification', {
  id: text('id').primaryKey(),
  identifier: text('identifier').notNull(),
  value: text('value').notNull(),
  expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
  createdAt: integer('created_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .notNull(),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
    .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
    .$onUpdate(() => new Date())
    .notNull(),
});

// =============================================================================
// AEI Tables (with userId for multi-tenancy)
// =============================================================================
export const repos = sqliteTable('repos', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  url: text('url').notNull(),
  transcriptCount: integer('transcript_count').default(0).notNull(),
  lastActivity: text('last_activity'), // ISO datetime string
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }), // Multi-tenant: link to BetterAuth user
  createdAt: integer('created_at', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
});

export const transcripts = sqliteTable('transcripts', {
  id: text('id').primaryKey(),
  repoId: text('repo_id').notNull().references(() => repos.id, { onDelete: 'cascade' }),
  sessionId: text('session_id'),
  events: text('events').notNull(), // JSON string
  createdAt: integer('created_at', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
  analyzed: integer('analyzed', { mode: 'boolean' }).default(false).notNull(),
  userId: text('user_id')
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }), // Multi-tenant
});

export const analysis = sqliteTable('analysis', {
  transcriptId: text('transcript_id').primaryKey().references(() => transcripts.id, { onDelete: 'cascade' }),
  retryCount: integer('retry_count').notNull(),
  errorCount: integer('error_count').notNull(),
  toolFailureRate: real('tool_failure_rate').notNull(),
  contextOverflows: integer('context_overflows').notNull(),
  healthScore: integer('health_score').notNull(),
  antiPatterns: text('anti_patterns').notNull(), // JSON
  recommendations: text('recommendations').notNull(), // JSON
  analyzedAt: integer('analyzed_at', { mode: 'timestamp' }).notNull().$defaultFn(() => new Date()),
});

// =============================================================================
// Relations (for Drizzle queries with joins)
// =============================================================================

// BetterAuth relations
export const userRelations = relations(user, ({ many }) => ({
  sessions: many(session),
  accounts: many(account),
  repos: many(repos),
  transcripts: many(transcripts),
}));

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, {
    fields: [session.userId],
    references: [user.id],
  }),
}));

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, {
    fields: [account.userId],
    references: [user.id],
  }),
}));

// AEI relations
export const reposRelations = relations(repos, ({ one, many }) => ({
  user: one(user, {
    fields: [repos.userId],
    references: [user.id],
  }),
  transcripts: many(transcripts),
}));

export const transcriptsRelations = relations(transcripts, ({ one }) => ({
  user: one(user, {
    fields: [transcripts.userId],
    references: [user.id],
  }),
  repo: one(repos, {
    fields: [transcripts.repoId],
    references: [repos.id],
  }),
  analysis: one(analysis, {
    fields: [transcripts.id],
    references: [analysis.transcriptId],
  }),
}));
