name: agentlogs
region: sfo3

services:
  - name: web
    github:
      repo: tomjnsn/agentlogs
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${db.DATABASE_URL}
      - key: S3_ENDPOINT
        scope: RUN_TIME
        value: CHANGE_ME
      - key: S3_BUCKET
        scope: RUN_TIME
        value: CHANGE_ME
      - key: S3_REGION
        scope: RUN_TIME
        value: CHANGE_ME
      - key: S3_ACCESS_KEY
        scope: RUN_TIME
        type: SECRET
        value: CHANGE_ME
      - key: S3_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
        value: CHANGE_ME
      - key: BETTER_AUTH_SECRET
        scope: RUN_TIME
        type: SECRET
        value: CHANGE_ME
      - key: WEB_URL
        scope: RUN_TIME
        value: CHANGE_ME
      - key: GITHUB_CLIENT_ID
        scope: RUN_TIME
        value: CHANGE_ME
      - key: GITHUB_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET
        value: CHANGE_ME

databases:
  - name: db
    engine: PG
    version: "16"
    size: db-s-1vcpu-1gb
    num_nodes: 1
