/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSplatRouteImport } from './routes/auth.$'
import { Route as ApiTranscriptsRouteImport } from './routes/api/transcripts'
import { Route as ApiIngestRouteImport } from './routes/api/ingest'
import { Route as ApiCommitTrackRouteImport } from './routes/api/commit-track'
import { Route as AppDeviceRouteImport } from './routes/_app/device'
import { Route as AppAppRouteImport } from './routes/_app/app'
import { Route as ApiTranscriptsClearRouteImport } from './routes/api/transcripts/clear'
import { Route as ApiBlobsSha256RouteImport } from './routes/api/blobs.$sha256'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AppTranscriptsIdRouteImport } from './routes/_app/transcripts.$id'
import { Route as AppSSessionIdRouteImport } from './routes/_app/s.$sessionId'
import { Route as AppReposIdRouteImport } from './routes/_app/repos.$id'
import { Route as AppPrivateCwdRouteImport } from './routes/_app/private.$cwd'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSplatRoute = AuthSplatRouteImport.update({
  id: '/auth/$',
  path: '/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscriptsRoute = ApiTranscriptsRouteImport.update({
  id: '/api/transcripts',
  path: '/api/transcripts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestRoute = ApiIngestRouteImport.update({
  id: '/api/ingest',
  path: '/api/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommitTrackRoute = ApiCommitTrackRouteImport.update({
  id: '/api/commit-track',
  path: '/api/commit-track',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDeviceRoute = AppDeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => AppRoute,
} as any)
const AppAppRoute = AppAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AppRoute,
} as any)
const ApiTranscriptsClearRoute = ApiTranscriptsClearRouteImport.update({
  id: '/clear',
  path: '/clear',
  getParentRoute: () => ApiTranscriptsRoute,
} as any)
const ApiBlobsSha256Route = ApiBlobsSha256RouteImport.update({
  id: '/api/blobs/$sha256',
  path: '/api/blobs/$sha256',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTranscriptsIdRoute = AppTranscriptsIdRouteImport.update({
  id: '/transcripts/$id',
  path: '/transcripts/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSSessionIdRoute = AppSSessionIdRouteImport.update({
  id: '/s/$sessionId',
  path: '/s/$sessionId',
  getParentRoute: () => AppRoute,
} as any)
const AppReposIdRoute = AppReposIdRouteImport.update({
  id: '/repos/$id',
  path: '/repos/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivateCwdRoute = AppPrivateCwdRouteImport.update({
  id: '/private/$cwd',
  path: '/private/$cwd',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppAppRoute
  '/device': typeof AppDeviceRoute
  '/api/commit-track': typeof ApiCommitTrackRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/transcripts': typeof ApiTranscriptsRouteWithChildren
  '/auth/$': typeof AuthSplatRoute
  '/private/$cwd': typeof AppPrivateCwdRoute
  '/repos/$id': typeof AppReposIdRoute
  '/s/$sessionId': typeof AppSSessionIdRoute
  '/transcripts/$id': typeof AppTranscriptsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blobs/$sha256': typeof ApiBlobsSha256Route
  '/api/transcripts/clear': typeof ApiTranscriptsClearRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppAppRoute
  '/device': typeof AppDeviceRoute
  '/api/commit-track': typeof ApiCommitTrackRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/transcripts': typeof ApiTranscriptsRouteWithChildren
  '/auth/$': typeof AuthSplatRoute
  '/private/$cwd': typeof AppPrivateCwdRoute
  '/repos/$id': typeof AppReposIdRoute
  '/s/$sessionId': typeof AppSSessionIdRoute
  '/transcripts/$id': typeof AppTranscriptsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blobs/$sha256': typeof ApiBlobsSha256Route
  '/api/transcripts/clear': typeof ApiTranscriptsClearRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/app': typeof AppAppRoute
  '/_app/device': typeof AppDeviceRoute
  '/api/commit-track': typeof ApiCommitTrackRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/transcripts': typeof ApiTranscriptsRouteWithChildren
  '/auth/$': typeof AuthSplatRoute
  '/_app/private/$cwd': typeof AppPrivateCwdRoute
  '/_app/repos/$id': typeof AppReposIdRoute
  '/_app/s/$sessionId': typeof AppSSessionIdRoute
  '/_app/transcripts/$id': typeof AppTranscriptsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blobs/$sha256': typeof ApiBlobsSha256Route
  '/api/transcripts/clear': typeof ApiTranscriptsClearRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/device'
    | '/api/commit-track'
    | '/api/ingest'
    | '/api/transcripts'
    | '/auth/$'
    | '/private/$cwd'
    | '/repos/$id'
    | '/s/$sessionId'
    | '/transcripts/$id'
    | '/api/auth/$'
    | '/api/blobs/$sha256'
    | '/api/transcripts/clear'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/device'
    | '/api/commit-track'
    | '/api/ingest'
    | '/api/transcripts'
    | '/auth/$'
    | '/private/$cwd'
    | '/repos/$id'
    | '/s/$sessionId'
    | '/transcripts/$id'
    | '/api/auth/$'
    | '/api/blobs/$sha256'
    | '/api/transcripts/clear'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/app'
    | '/_app/device'
    | '/api/commit-track'
    | '/api/ingest'
    | '/api/transcripts'
    | '/auth/$'
    | '/_app/private/$cwd'
    | '/_app/repos/$id'
    | '/_app/s/$sessionId'
    | '/_app/transcripts/$id'
    | '/api/auth/$'
    | '/api/blobs/$sha256'
    | '/api/transcripts/clear'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiCommitTrackRoute: typeof ApiCommitTrackRoute
  ApiIngestRoute: typeof ApiIngestRoute
  ApiTranscriptsRoute: typeof ApiTranscriptsRouteWithChildren
  AuthSplatRoute: typeof AuthSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBlobsSha256Route: typeof ApiBlobsSha256Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$': {
      id: '/auth/$'
      path: '/auth/$'
      fullPath: '/auth/$'
      preLoaderRoute: typeof AuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcripts': {
      id: '/api/transcripts'
      path: '/api/transcripts'
      fullPath: '/api/transcripts'
      preLoaderRoute: typeof ApiTranscriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest': {
      id: '/api/ingest'
      path: '/api/ingest'
      fullPath: '/api/ingest'
      preLoaderRoute: typeof ApiIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/commit-track': {
      id: '/api/commit-track'
      path: '/api/commit-track'
      fullPath: '/api/commit-track'
      preLoaderRoute: typeof ApiCommitTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/device': {
      id: '/_app/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof AppDeviceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app': {
      id: '/_app/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAppRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/transcripts/clear': {
      id: '/api/transcripts/clear'
      path: '/clear'
      fullPath: '/api/transcripts/clear'
      preLoaderRoute: typeof ApiTranscriptsClearRouteImport
      parentRoute: typeof ApiTranscriptsRoute
    }
    '/api/blobs/$sha256': {
      id: '/api/blobs/$sha256'
      path: '/api/blobs/$sha256'
      fullPath: '/api/blobs/$sha256'
      preLoaderRoute: typeof ApiBlobsSha256RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/transcripts/$id': {
      id: '/_app/transcripts/$id'
      path: '/transcripts/$id'
      fullPath: '/transcripts/$id'
      preLoaderRoute: typeof AppTranscriptsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/s/$sessionId': {
      id: '/_app/s/$sessionId'
      path: '/s/$sessionId'
      fullPath: '/s/$sessionId'
      preLoaderRoute: typeof AppSSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/repos/$id': {
      id: '/_app/repos/$id'
      path: '/repos/$id'
      fullPath: '/repos/$id'
      preLoaderRoute: typeof AppReposIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/private/$cwd': {
      id: '/_app/private/$cwd'
      path: '/private/$cwd'
      fullPath: '/private/$cwd'
      preLoaderRoute: typeof AppPrivateCwdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAppRoute: typeof AppAppRoute
  AppDeviceRoute: typeof AppDeviceRoute
  AppPrivateCwdRoute: typeof AppPrivateCwdRoute
  AppReposIdRoute: typeof AppReposIdRoute
  AppSSessionIdRoute: typeof AppSSessionIdRoute
  AppTranscriptsIdRoute: typeof AppTranscriptsIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppRoute: AppAppRoute,
  AppDeviceRoute: AppDeviceRoute,
  AppPrivateCwdRoute: AppPrivateCwdRoute,
  AppReposIdRoute: AppReposIdRoute,
  AppSSessionIdRoute: AppSSessionIdRoute,
  AppTranscriptsIdRoute: AppTranscriptsIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiTranscriptsRouteChildren {
  ApiTranscriptsClearRoute: typeof ApiTranscriptsClearRoute
}

const ApiTranscriptsRouteChildren: ApiTranscriptsRouteChildren = {
  ApiTranscriptsClearRoute: ApiTranscriptsClearRoute,
}

const ApiTranscriptsRouteWithChildren = ApiTranscriptsRoute._addFileChildren(
  ApiTranscriptsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiCommitTrackRoute: ApiCommitTrackRoute,
  ApiIngestRoute: ApiIngestRoute,
  ApiTranscriptsRoute: ApiTranscriptsRouteWithChildren,
  AuthSplatRoute: AuthSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBlobsSha256Route: ApiBlobsSha256Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
