/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSplatRouteImport } from './routes/auth.$'
import { Route as ApiTunnelRouteImport } from './routes/api/tunnel'
import { Route as ApiTranscriptsRouteImport } from './routes/api/transcripts'
import { Route as ApiIngestRouteImport } from './routes/api/ingest'
import { Route as ApiCommitTrackRouteImport } from './routes/api/commit-track'
import { Route as AppAppIndexRouteImport } from './routes/_app/app/index'
import { Route as ApiTranscriptsClearRouteImport } from './routes/api/transcripts/clear'
import { Route as ApiBlobsSha256RouteImport } from './routes/api/blobs.$sha256'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AppSSessionIdRouteImport } from './routes/_app/s.$sessionId'
import { Route as AppJoinCodeRouteImport } from './routes/_app/join.$code'
import { Route as AppAppTeamRouteImport } from './routes/_app/app/team'
import { Route as AppAppDeviceRouteImport } from './routes/_app/app/device'
import { Route as AppAppAdminRouteImport } from './routes/_app/app/admin'
import { Route as AppAppPrivateCwdRouteImport } from './routes/_app/app/private.$cwd'
import { Route as AppAppLogsIdRouteImport } from './routes/_app/app/logs.$id'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSplatRoute = AuthSplatRouteImport.update({
  id: '/auth/$',
  path: '/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTunnelRoute = ApiTunnelRouteImport.update({
  id: '/api/tunnel',
  path: '/api/tunnel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscriptsRoute = ApiTranscriptsRouteImport.update({
  id: '/api/transcripts',
  path: '/api/transcripts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestRoute = ApiIngestRouteImport.update({
  id: '/api/ingest',
  path: '/api/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommitTrackRoute = ApiCommitTrackRouteImport.update({
  id: '/api/commit-track',
  path: '/api/commit-track',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppIndexRoute = AppAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AppRoute,
} as any)
const ApiTranscriptsClearRoute = ApiTranscriptsClearRouteImport.update({
  id: '/clear',
  path: '/clear',
  getParentRoute: () => ApiTranscriptsRoute,
} as any)
const ApiBlobsSha256Route = ApiBlobsSha256RouteImport.update({
  id: '/api/blobs/$sha256',
  path: '/api/blobs/$sha256',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSSessionIdRoute = AppSSessionIdRouteImport.update({
  id: '/s/$sessionId',
  path: '/s/$sessionId',
  getParentRoute: () => AppRoute,
} as any)
const AppJoinCodeRoute = AppJoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => AppRoute,
} as any)
const AppAppTeamRoute = AppAppTeamRouteImport.update({
  id: '/app/team',
  path: '/app/team',
  getParentRoute: () => AppRoute,
} as any)
const AppAppDeviceRoute = AppAppDeviceRouteImport.update({
  id: '/app/device',
  path: '/app/device',
  getParentRoute: () => AppRoute,
} as any)
const AppAppAdminRoute = AppAppAdminRouteImport.update({
  id: '/app/admin',
  path: '/app/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAppPrivateCwdRoute = AppAppPrivateCwdRouteImport.update({
  id: '/app/private/$cwd',
  path: '/app/private/$cwd',
  getParentRoute: () => AppRoute,
} as any)
const AppAppLogsIdRoute = AppAppLogsIdRouteImport.update({
  id: '/app/logs/$id',
  path: '/app/logs/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/waitlist': typeof WaitlistRoute
  '/api/commit-track': typeof ApiCommitTrackRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/transcripts': typeof ApiTranscriptsRouteWithChildren
  '/api/tunnel': typeof ApiTunnelRoute
  '/auth/$': typeof AuthSplatRoute
  '/app/admin': typeof AppAppAdminRoute
  '/app/device': typeof AppAppDeviceRoute
  '/app/team': typeof AppAppTeamRoute
  '/join/$code': typeof AppJoinCodeRoute
  '/s/$sessionId': typeof AppSSessionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blobs/$sha256': typeof ApiBlobsSha256Route
  '/api/transcripts/clear': typeof ApiTranscriptsClearRoute
  '/app': typeof AppAppIndexRoute
  '/app/logs/$id': typeof AppAppLogsIdRoute
  '/app/private/$cwd': typeof AppAppPrivateCwdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/waitlist': typeof WaitlistRoute
  '/api/commit-track': typeof ApiCommitTrackRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/transcripts': typeof ApiTranscriptsRouteWithChildren
  '/api/tunnel': typeof ApiTunnelRoute
  '/auth/$': typeof AuthSplatRoute
  '/app/admin': typeof AppAppAdminRoute
  '/app/device': typeof AppAppDeviceRoute
  '/app/team': typeof AppAppTeamRoute
  '/join/$code': typeof AppJoinCodeRoute
  '/s/$sessionId': typeof AppSSessionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blobs/$sha256': typeof ApiBlobsSha256Route
  '/api/transcripts/clear': typeof ApiTranscriptsClearRoute
  '/app': typeof AppAppIndexRoute
  '/app/logs/$id': typeof AppAppLogsIdRoute
  '/app/private/$cwd': typeof AppAppPrivateCwdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/waitlist': typeof WaitlistRoute
  '/api/commit-track': typeof ApiCommitTrackRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/transcripts': typeof ApiTranscriptsRouteWithChildren
  '/api/tunnel': typeof ApiTunnelRoute
  '/auth/$': typeof AuthSplatRoute
  '/_app/app/admin': typeof AppAppAdminRoute
  '/_app/app/device': typeof AppAppDeviceRoute
  '/_app/app/team': typeof AppAppTeamRoute
  '/_app/join/$code': typeof AppJoinCodeRoute
  '/_app/s/$sessionId': typeof AppSSessionIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blobs/$sha256': typeof ApiBlobsSha256Route
  '/api/transcripts/clear': typeof ApiTranscriptsClearRoute
  '/_app/app/': typeof AppAppIndexRoute
  '/_app/app/logs/$id': typeof AppAppLogsIdRoute
  '/_app/app/private/$cwd': typeof AppAppPrivateCwdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/waitlist'
    | '/api/commit-track'
    | '/api/ingest'
    | '/api/transcripts'
    | '/api/tunnel'
    | '/auth/$'
    | '/app/admin'
    | '/app/device'
    | '/app/team'
    | '/join/$code'
    | '/s/$sessionId'
    | '/api/auth/$'
    | '/api/blobs/$sha256'
    | '/api/transcripts/clear'
    | '/app'
    | '/app/logs/$id'
    | '/app/private/$cwd'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/waitlist'
    | '/api/commit-track'
    | '/api/ingest'
    | '/api/transcripts'
    | '/api/tunnel'
    | '/auth/$'
    | '/app/admin'
    | '/app/device'
    | '/app/team'
    | '/join/$code'
    | '/s/$sessionId'
    | '/api/auth/$'
    | '/api/blobs/$sha256'
    | '/api/transcripts/clear'
    | '/app'
    | '/app/logs/$id'
    | '/app/private/$cwd'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/waitlist'
    | '/api/commit-track'
    | '/api/ingest'
    | '/api/transcripts'
    | '/api/tunnel'
    | '/auth/$'
    | '/_app/app/admin'
    | '/_app/app/device'
    | '/_app/app/team'
    | '/_app/join/$code'
    | '/_app/s/$sessionId'
    | '/api/auth/$'
    | '/api/blobs/$sha256'
    | '/api/transcripts/clear'
    | '/_app/app/'
    | '/_app/app/logs/$id'
    | '/_app/app/private/$cwd'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  WaitlistRoute: typeof WaitlistRoute
  ApiCommitTrackRoute: typeof ApiCommitTrackRoute
  ApiIngestRoute: typeof ApiIngestRoute
  ApiTranscriptsRoute: typeof ApiTranscriptsRouteWithChildren
  ApiTunnelRoute: typeof ApiTunnelRoute
  AuthSplatRoute: typeof AuthSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBlobsSha256Route: typeof ApiBlobsSha256Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$': {
      id: '/auth/$'
      path: '/auth/$'
      fullPath: '/auth/$'
      preLoaderRoute: typeof AuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tunnel': {
      id: '/api/tunnel'
      path: '/api/tunnel'
      fullPath: '/api/tunnel'
      preLoaderRoute: typeof ApiTunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcripts': {
      id: '/api/transcripts'
      path: '/api/transcripts'
      fullPath: '/api/transcripts'
      preLoaderRoute: typeof ApiTranscriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest': {
      id: '/api/ingest'
      path: '/api/ingest'
      fullPath: '/api/ingest'
      preLoaderRoute: typeof ApiIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/commit-track': {
      id: '/api/commit-track'
      path: '/api/commit-track'
      fullPath: '/api/commit-track'
      preLoaderRoute: typeof ApiCommitTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/app/': {
      id: '/_app/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/transcripts/clear': {
      id: '/api/transcripts/clear'
      path: '/clear'
      fullPath: '/api/transcripts/clear'
      preLoaderRoute: typeof ApiTranscriptsClearRouteImport
      parentRoute: typeof ApiTranscriptsRoute
    }
    '/api/blobs/$sha256': {
      id: '/api/blobs/$sha256'
      path: '/api/blobs/$sha256'
      fullPath: '/api/blobs/$sha256'
      preLoaderRoute: typeof ApiBlobsSha256RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/s/$sessionId': {
      id: '/_app/s/$sessionId'
      path: '/s/$sessionId'
      fullPath: '/s/$sessionId'
      preLoaderRoute: typeof AppSSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/join/$code': {
      id: '/_app/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof AppJoinCodeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/team': {
      id: '/_app/app/team'
      path: '/app/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AppAppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/device': {
      id: '/_app/app/device'
      path: '/app/device'
      fullPath: '/app/device'
      preLoaderRoute: typeof AppAppDeviceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/admin': {
      id: '/_app/app/admin'
      path: '/app/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/private/$cwd': {
      id: '/_app/app/private/$cwd'
      path: '/app/private/$cwd'
      fullPath: '/app/private/$cwd'
      preLoaderRoute: typeof AppAppPrivateCwdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/app/logs/$id': {
      id: '/_app/app/logs/$id'
      path: '/app/logs/$id'
      fullPath: '/app/logs/$id'
      preLoaderRoute: typeof AppAppLogsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAppAdminRoute: typeof AppAppAdminRoute
  AppAppDeviceRoute: typeof AppAppDeviceRoute
  AppAppTeamRoute: typeof AppAppTeamRoute
  AppJoinCodeRoute: typeof AppJoinCodeRoute
  AppSSessionIdRoute: typeof AppSSessionIdRoute
  AppAppIndexRoute: typeof AppAppIndexRoute
  AppAppLogsIdRoute: typeof AppAppLogsIdRoute
  AppAppPrivateCwdRoute: typeof AppAppPrivateCwdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppAdminRoute: AppAppAdminRoute,
  AppAppDeviceRoute: AppAppDeviceRoute,
  AppAppTeamRoute: AppAppTeamRoute,
  AppJoinCodeRoute: AppJoinCodeRoute,
  AppSSessionIdRoute: AppSSessionIdRoute,
  AppAppIndexRoute: AppAppIndexRoute,
  AppAppLogsIdRoute: AppAppLogsIdRoute,
  AppAppPrivateCwdRoute: AppAppPrivateCwdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiTranscriptsRouteChildren {
  ApiTranscriptsClearRoute: typeof ApiTranscriptsClearRoute
}

const ApiTranscriptsRouteChildren: ApiTranscriptsRouteChildren = {
  ApiTranscriptsClearRoute: ApiTranscriptsClearRoute,
}

const ApiTranscriptsRouteWithChildren = ApiTranscriptsRoute._addFileChildren(
  ApiTranscriptsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  WaitlistRoute: WaitlistRoute,
  ApiCommitTrackRoute: ApiCommitTrackRoute,
  ApiIngestRoute: ApiIngestRoute,
  ApiTranscriptsRoute: ApiTranscriptsRouteWithChildren,
  ApiTunnelRoute: ApiTunnelRoute,
  AuthSplatRoute: AuthSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBlobsSha256Route: ApiBlobsSha256Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
