/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TranscriptsIdRouteImport } from './routes/transcripts.$id'
import { Route as ReposIdRouteImport } from './routes/repos.$id'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TranscriptsIdRoute = TranscriptsIdRouteImport.update({
  id: '/transcripts/$id',
  path: '/transcripts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposIdRoute = ReposIdRouteImport.update({
  id: '/repos/$id',
  path: '/repos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/repos/$id': typeof ReposIdRoute
  '/transcripts/$id': typeof TranscriptsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/repos/$id': typeof ReposIdRoute
  '/transcripts/$id': typeof TranscriptsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/repos/$id': typeof ReposIdRoute
  '/transcripts/$id': typeof TranscriptsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign-in' | '/repos/$id' | '/transcripts/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign-in' | '/repos/$id' | '/transcripts/$id'
  id: '__root__' | '/' | '/sign-in' | '/repos/$id' | '/transcripts/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  ReposIdRoute: typeof ReposIdRoute
  TranscriptsIdRoute: typeof TranscriptsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transcripts/$id': {
      id: '/transcripts/$id'
      path: '/transcripts/$id'
      fullPath: '/transcripts/$id'
      preLoaderRoute: typeof TranscriptsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/$id': {
      id: '/repos/$id'
      path: '/repos/$id'
      fullPath: '/repos/$id'
      preLoaderRoute: typeof ReposIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  ReposIdRoute: ReposIdRoute,
  TranscriptsIdRoute: TranscriptsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
